# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [ ]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [2]:
import numpy as np
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [3]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [6]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [9]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [11]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones([3,5])
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [13]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [ ]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

In [14]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [15]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.18959324 0.15698083 0.07182768 0.71355214 0.46340034]
 [0.37779489 0.69878508 0.7641519  0.84707381 0.97788775]
 [0.5162122  0.57032808 0.32960722 0.67729356 0.57314826]
 [0.1043319  0.90326339 0.31024833 0.19154426 0.16716   ]
 [0.43269625 0.70445852 0.27101024 0.26557872 0.10440802]]

[[-0.10609889  0.52042079 -1.76597952  0.96436189 -0.07746223]
 [ 0.09876243 -0.40229554 -1.97558973  0.3420532   1.48937252]
 [-0.72756903 -0.13019952 -0.06454678 -0.07940914  2.65152569]
 [-0.80652715 -1.7070331   1.59576201 -0.69297634  1.95973015]
 [-1.84767517  0.37430114  0.08938954  0.59306993 -0.09154064]
 [ 0.25888359  0.82899535  0.01417064 -1.49666847  0.71160916]
 [ 0.37961117  0.27000463 -1.30390899  0.65094919  1.21214348]
 [ 1.38855538 -0.40487828  0.62072469  0.38126892 -1.14541433]
 [ 0.40576596  0.63536078  2.25344665  0.17881548 -0.35006825]
 [-1.57336939  0.97320078  0.99131402  0.68963986 -0.89437064]]


In [16]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.4552934635783805
1.0461711714063424


In [17]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.07182767753061836
2.651525687259837


In [ ]:
# break here for next video!

In [18]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[-0.16790025  0.59735022 -0.78618046 -0.08057934 -2.29915059  1.1288401
 -0.41034987 -0.53467057  0.87116341 -0.24013165  0.83623138  0.20128623
 -0.47884674  2.11739671  0.02338258  1.1856703  -0.20442068 -2.21562551
 -1.92472207]
-0.4103498679151754


In [19]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[-2.29915059  1.1288401  -0.41034987 -0.53467057  0.87116341]


In [20]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[-0.16790025 -0.08057934 -0.41034987 -0.24013165 -0.47884674]


In [21]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.18959324 0.15698083 0.07182768 0.71355214 0.46340034]
 [0.37779489 0.69878508 0.7641519  0.84707381 0.97788775]
 [0.5162122  0.57032808 0.32960722 0.67729356 0.57314826]
 [0.1043319  0.90326339 0.31024833 0.19154426 0.16716   ]
 [0.43269625 0.70445852 0.27101024 0.26557872 0.10440802]]
0.7641518958576526
0.7641518958576526


In [ ]:
print(rand_mat[0:2,1:3])

In [22]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[-0.16790025  0.59735022 -0.78618046 -0.08057934 -2.29915059  1.1288401
 -0.41034987 -0.53467057  0.87116341 -0.24013165  0.83623138  0.20128623
 -0.47884674  2.11739671  0.02338258  1.1856703  -0.20442068 -2.21562551
 -1.92472207]

[-0.16790025  0.59735022 -0.78618046  4.          4.          1.1288401
 -0.41034987 -0.53467057  0.87116341 -0.24013165  0.83623138  0.20128623
 -0.47884674  2.11739671  0.02338258  1.1856703  -0.20442068 -2.21562551
 -1.92472207]

[-0.16790025  0.59735022 -0.78618046  1.          2.          1.1288401
 -0.41034987 -0.53467057  0.87116341 -0.24013165  0.83623138  0.20128623
 -0.47884674  2.11739671  0.02338258  1.1856703  -0.20442068 -2.21562551
 -1.92472207]


In [23]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.18959324 0.15698083 0.07182768 0.71355214 0.46340034]
 [0.37779489 0.69878508 0.7641519  0.84707381 0.97788775]
 [0.5162122  0.57032808 0.32960722 0.67729356 0.57314826]
 [0.1043319  0.90326339 0.31024833 0.19154426 0.16716   ]
 [0.43269625 0.70445852 0.27101024 0.26557872 0.10440802]]

[[0.18959324 0.15698083 0.07182768 0.71355214 0.46340034]
 [0.37779489 0.69878508 0.7641519  0.         0.        ]
 [0.5162122  0.57032808 0.32960722 0.         0.        ]
 [0.1043319  0.90326339 0.31024833 0.19154426 0.16716   ]
 [0.43269625 0.70445852 0.27101024 0.26557872 0.10440802]]


In [24]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.18959324 0.15698083 0.07182768]
 [0.37779489 0.69878508 0.7641519 ]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [25]:
print(rand_mat)

[[3.         3.         3.         0.71355214 0.46340034]
 [3.         3.         3.         0.         0.        ]
 [0.5162122  0.57032808 0.32960722 0.         0.        ]
 [0.1043319  0.90326339 0.31024833 0.19154426 0.16716   ]
 [0.43269625 0.70445852 0.27101024 0.26557872 0.10440802]]


In [ ]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


In [ ]:
# break here for next video

In [26]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[-0.31027457 -1.3989834   0.59929234  0.55834343 -0.43950555  1.20901333
 -0.83953502 -0.84500575 -0.22593629 -1.82783929  1.06035809  1.71027491
  0.3610966   0.04068522 -1.39703166]
[False False  True  True False  True False False False False  True  True
  True  True False]
[0.59929234 0.55834343 1.20901333 1.06035809 1.71027491 0.3610966
 0.04068522]


In [27]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[-0.10609889  0.52042079 -1.76597952  0.96436189 -0.07746223]
 [ 0.09876243 -0.40229554 -1.97558973  0.3420532   1.48937252]
 [-0.72756903 -0.13019952 -0.06454678 -0.07940914  2.65152569]
 [-0.80652715 -1.7070331   1.59576201 -0.69297634  1.95973015]
 [-1.84767517  0.37430114  0.08938954  0.59306993 -0.09154064]
 [ 0.25888359  0.82899535  0.01417064 -1.49666847  0.71160916]
 [ 0.37961117  0.27000463 -1.30390899  0.65094919  1.21214348]
 [ 1.38855538 -0.40487828  0.62072469  0.38126892 -1.14541433]
 [ 0.40576596  0.63536078  2.25344665  0.17881548 -0.35006825]
 [-1.57336939  0.97320078  0.99131402  0.68963986 -0.89437064]]
[0.52042079 0.96436189 0.09876243 0.3420532  1.48937252 2.65152569
 1.59576201 1.95973015 0.37430114 0.08938954 0.59306993 0.25888359
 0.82899535 0.01417064 0.71160916 0.37961117 0.27000463 0.65094919
 1.21214348 1.38855538 0.62072469 0.38126892 0.40576596 0.63536078
 2.25344665 0.17881548 0.97320078 0.99131402 0.68963986]


In [28]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[-0.31027457 -1.3989834   0.59929234  0.55834343 -0.43950555  1.20901333
 -0.83953502 -0.84500575 -0.22593629 -1.82783929  1.06035809  1.71027491
  0.3610966   0.04068522 -1.39703166]

[-0.31027457 -1.3989834  -5.         -5.         -0.43950555 -5.
 -0.83953502 -0.84500575 -0.22593629 -1.82783929 -5.         -5.
  0.3610966   0.04068522 -1.39703166]


In [30]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [31]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [32]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[-0.10609889  0.52042079 -1.76597952  0.96436189 -0.07746223]
 [ 0.09876243 -0.40229554 -1.97558973  0.3420532   1.48937252]
 [-0.72756903 -0.13019952 -0.06454678 -0.07940914  2.65152569]
 [-0.80652715 -1.7070331   1.59576201 -0.69297634  1.95973015]
 [-1.84767517  0.37430114  0.08938954  0.59306993 -0.09154064]
 [ 0.25888359  0.82899535  0.01417064 -1.49666847  0.71160916]
 [ 0.37961117  0.27000463 -1.30390899  0.65094919  1.21214348]
 [ 1.38855538 -0.40487828  0.62072469  0.38126892 -1.14541433]
 [ 0.40576596  0.63536078  2.25344665  0.17881548 -0.35006825]
 [-1.57336939  0.97320078  0.99131402  0.68963986 -0.89437064]]



In [33]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.71355214 0.46340034]
 [3.         3.         3.         0.         0.        ]
 [0.5162122  0.57032808 0.32960722 0.         0.        ]
 [0.1043319  0.90326339 0.31024833 0.19154426 0.16716   ]
 [0.43269625 0.70445852 0.27101024 0.26557872 0.10440802]]

[[-0.10609889  0.52042079 -1.76597952  0.96436189 -0.07746223]
 [ 0.09876243 -0.40229554 -1.97558973  0.3420532   1.48937252]
 [-0.72756903 -0.13019952 -0.06454678 -0.07940914  2.65152569]
 [-0.80652715 -1.7070331   1.59576201 -0.69297634  1.95973015]
 [-1.84767517  0.37430114  0.08938954  0.59306993 -0.09154064]
 [ 0.25888359  0.82899535  0.01417064 -1.49666847  0.71160916]
 [ 0.37961117  0.27000463 -1.30390899  0.65094919  1.21214348]
 [ 1.38855538 -0.40487828  0.62072469  0.38126892 -1.14541433]
 [ 0.40576596  0.63536078  2.25344665  0.17881548 -0.35006825]
 [-1.57336939  0.97320078  0.99131402  0.68963986 -0.89437064]]
[[3.         3.         3.         0.71355214 0.46340034]
 [3.         3.    

In [34]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.71355214 0.46340034]
 [3.         3.         3.         0.         0.        ]
 [0.5162122  0.57032808 0.32960722 0.         0.        ]
 [0.1043319  0.90326339 0.31024833 0.19154426 0.16716   ]
 [0.43269625 0.70445852 0.27101024 0.26557872 0.10440802]]

[[3.         3.         3.         0.71355214 0.46340034]
 [3.         3.         3.         0.         0.        ]
 [0.5162122  0.57032808 0.32960722 0.         0.        ]
 [0.1043319  0.90326339 0.31024833 0.19154426 0.16716   ]
 [0.43269625 0.70445852 0.27101024 0.26557872 0.10440802]]
